# Generated by Django 2.0.4 on 2018-07-18 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20180711_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='account',
            name='withdrawable_balance',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='openid_channel',
            field=models.IntegerField(verbose_name=[(0, 'WECHAT'), (1, 'ALIPAY')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.IntegerField(default=0, verbose_name=[(0, 'USING'), (1, 'DISABLED')]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_charge',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='couponrule',
            name='discount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='couponrule',
            name='min_charge',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='marketer',
            name='inviter_type',
            field=models.IntegerField(verbose_name=[(0, 'MARKETER'), (1, 'SALESMAN')]),
        ),
        migrations.AlterField(
            model_name='merchantadmin',
            name='merchant_admin_type',
            field=models.IntegerField(verbose_name=[(0, 'ADMIN'), (1, 'CASHIER')]),
        ),
        migrations.AlterField(
            model_name='merchantadmin',
            name='status',
            field=models.IntegerField(verbose_name=[(0, 'USING'), (1, 'DISABLED')]),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.IntegerField(verbose_name=[(0, 'DELETE'), (1, 'HANDLED'), (2, 'UNHANDLED')]),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.IntegerField(verbose_name=[(1, 'AREA_WITHOUT_MARKETER')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='inviter_share',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='originator_share',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_channel',
            field=models.IntegerField(verbose_name=[(0, 'WECHAT'), (1, 'ALIPAY')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='platform_share',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='status',
            field=models.IntegerField(verbose_name=[(0, 'USING'), (1, 'DISABLED')]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_after_transaction',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(verbose_name=[(0, 'PLATFORM_RECEIVE'), (1, 'PLATFORM_EXPEND_MERCHANT_RECEIVE'), (2, 'MERCHANT_RECEIVE'), (3, 'MERCHANT_REFUND'), (4, 'PLATFORM_EARNING_MERCHANT_REFUND'), (5, 'PLATFORM_REFUND'), (6, 'PLATFORM_EXPEND_MERCHANT_SHARE'), (7, 'MERCHANT_SHARE'), (8, 'PLATFORM_EXPEND_MARKETER_SHARE'), (9, 'MARKETER_SHARE'), (10, 'PLATFORM_EXPEND_PLATFORM_SHARE'), (11, 'PLATFORM_SHARE'), (12, 'MERCHANT_WITHDRAW'), (13, 'MARKETER_WITHDRAW')]),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
