# Generated by Django 2.0.6 on 2018-07-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_auto_20180719_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='bank_account_name',
        ),
        migrations.AddField(
            model_name='account',
            name='real_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='bank_card_number',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='bank_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
