# Generated by Django 2.0.4 on 2018-07-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_auto_20180725_1551'),
        ('common', '0020_auto_20180727_1045')
    ]

    operations = [
        migrations.AddField(
            model_name='merchantmarketership',
            name='audit_info',
            field=models.CharField(default='', max_length=256),
        ),
    ]
