# Generated by Django 2.0.6 on 2018-07-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_auto_20180725_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantadmin',
            name='wechat_avatar_url',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='merchantadmin',
            name='wechat_nickname',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
