# Generated by Django 2.0.6 on 2018-07-30 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_merchantmarketership_audit_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionAccountReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(verbose_name=[(0, 'DELETE'), (1, 'USING')])),
                ('rule_name', models.CharField(max_length=60, null=True)),
                ('question_text', models.CharField(max_length=30, null=True)),
                ('reply_rule', models.IntegerField(verbose_name=[(0, 'NOT_MATCH'), (1, 'PARTIAL'), (2, 'COMPLETE')])),
                ('reply_text', models.CharField(max_length=300, null=True)),
                ('reply_type', models.IntegerField(verbose_name=[(0, 'KEY_WORD'), (1, 'BE_PAID_ATTENTION'), (2, 'RECEIVED')])),
                ('reply_account', models.IntegerField(verbose_name=[(0, 'USER'), (1, 'MERCHANT'), (2, 'MARKETER')])),
            ],
        ),
    ]
