# Generated by Django 2.0.4 on 2018-07-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_merchantmarketership_audit_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='coupon_granted',
            field=models.BooleanField(default=False),
        ),
    ]
