# Generated by Django 2.0.4 on 2018-07-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_payment_coupon_granted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='location_lat',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='location_lon',
            field=models.FloatField(db_index=True),
        ),
    ]
