# Generated by Django 2.0.4 on 2018-08-06 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_auto_20180728_2052'),
        ('common', '0023_auto_20180802_1556'),
    ]

    operations = [
    ]
