# Generated by Django 2.0.4 on 2018-08-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_auto_20180815_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='openid_channel',
            field=models.IntegerField(choices=[(0, 'WECHAT'), (1, 'ALIPAY')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.IntegerField(choices=[(0, 'USING'), (1, 'DISABLED')], default=0),
        ),
        migrations.AlterField(
            model_name='marketer',
            name='inviter_type',
            field=models.IntegerField(choices=[(0, 'MARKETER'), (1, 'SALESMAN')]),
        ),
        migrations.AlterField(
            model_name='merchantadmin',
            name='merchant_admin_type',
            field=models.IntegerField(choices=[(0, 'ADMIN'), (1, 'CASHIER')]),
        ),
        migrations.AlterField(
            model_name='merchantadmin',
            name='status',
            field=models.IntegerField(choices=[(0, 'USING'), (1, 'DISABLED')]),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.IntegerField(choices=[(0, 'DELETE'), (1, 'HANDLED'), (2, 'UNHANDLED')]),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.IntegerField(choices=[(1, 'AREA_WITHOUT_MARKETER')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_channel',
            field=models.IntegerField(choices=[(0, 'WECHAT'), (1, 'ALIPAY')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.IntegerField(choices=[(0, 'UNPAID'), (1, 'FROZEN'), (2, 'REFUND_REQUESTED'), (3, 'REFUND'), (4, 'REFUND_FAILED'), (5, 'FINISHED'), (6, 'CANCELLED')]),
        ),
        migrations.AlterField(
            model_name='subscriptionaccountreply',
            name='reply_account',
            field=models.IntegerField(choices=[(0, 'USER'), (1, 'MERCHANT'), (2, 'MARKETER')]),
        ),
        migrations.AlterField(
            model_name='subscriptionaccountreply',
            name='reply_rule',
            field=models.IntegerField(choices=[(0, 'NOT_MATCH'), (1, 'PARTIAL'), (2, 'COMPLETE')]),
        ),
        migrations.AlterField(
            model_name='subscriptionaccountreply',
            name='reply_type',
            field=models.IntegerField(choices=[(0, 'KEY_WORD'), (1, 'BE_PAID_ATTENTION'), (2, 'RECEIVED')]),
        ),
        migrations.AlterField(
            model_name='subscriptionaccountreply',
            name='status',
            field=models.IntegerField(choices=[(0, 'DELETE'), (1, 'USING')]),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='status',
            field=models.IntegerField(choices=[(0, 'USING'), (1, 'DISABLED')]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(0, 'PLATFORM_RECEIVE'), (1, 'PLATFORM_EXPEND_MERCHANT_RECEIVE'), (2, 'MERCHANT_RECEIVE'), (3, 'MERCHANT_REFUND'), (4, 'PLATFORM_EARNING_MERCHANT_REFUND'), (5, 'PLATFORM_REFUND'), (6, 'PLATFORM_EXPEND_MERCHANT_SHARE'), (7, 'MERCHANT_SHARE'), (8, 'PLATFORM_EXPEND_MARKETER_SHARE'), (9, 'MARKETER_SHARE'), (10, 'PLATFORM_EXPEND_PLATFORM_SHARE'), (11, 'PLATFORM_SHARE'), (12, 'MERCHANT_WITHDRAW'), (13, 'MARKETER_WITHDRAW')]),
        ),
    ]
