# Generated by Django 2.0.4 on 2018-08-31 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_auto_20180829_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='update_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='marketer',
            name='phone',
            field=models.CharField(db_index=True, default='', max_length=32),
        ),
    ]
