# Generated by Django 2.0.4 on 2018-08-31 17:24

import common.encrypt_fileds
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0028_auto_20180831_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='openid',
            field=common.encrypt_fileds.EncryptedCharField(db_index=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='marketer',
            name='wechat_openid',
            field=common.encrypt_fileds.EncryptedCharField(db_index=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='merchantadmin',
            name='wechat_openid',
            field=common.encrypt_fileds.EncryptedCharField(db_index=True, max_length=128, unique=True),
        ),
    ]
