# Generated by Django 2.0.4 on 2018-09-17 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_auto_20180831_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='alipay_balance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='alipay_withdrawable_balance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchantadmin',
            name='alipay_user_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='merchantadmin',
            name='alipay_userid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='withdraw_type',
            field=models.IntegerField(choices=[(0, 'WECHAT'), (1, 'ALIPAY')], default=0),
            preserve_default=False,
        ),
    ]
