# Generated by Django 2.0.4 on 2018-10-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_auto_20180913_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('common.account',),
        ),
        migrations.AddField(
            model_name='marketer',
            name='alipay_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
