# Generated by Django 2.0.4 on 2018-10-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0032_auto_20181010_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='photo_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
