# Generated by Django 2.0.4 on 2018-10-11 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0032_auto_20181010_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRecord',
            fields=[
                ('serial_number', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('account_number', models.CharField(db_index=True, max_length=128)),
                ('account_name', models.CharField(db_index=True, max_length=64)),
                ('wechat_unionid', models.CharField(db_index=True, max_length=128)),
                ('status', models.IntegerField(choices=[(0, 'PROCESSING'), (1, 'FAILED'), (2, 'FINISHED')])),
                ('amount', models.IntegerField()),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(0, 'PLATFORM_RECEIVE'), (1, 'PLATFORM_EXPEND_MERCHANT_RECEIVE'), (2, 'MERCHANT_RECEIVE'), (3, 'MERCHANT_REFUND'), (4, 'PLATFORM_EARNING_MERCHANT_REFUND'), (5, 'PLATFORM_REFUND'), (6, 'PLATFORM_EXPEND_MERCHANT_SHARE'), (7, 'MERCHANT_SHARE'), (8, 'PLATFORM_EXPEND_MARKETER_SHARE'), (9, 'MARKETER_SHARE'), (10, 'PLATFORM_EXPEND_PLATFORM_SHARE'), (11, 'PLATFORM_SHARE'), (12, 'MERCHANT_WITHDRAW'), (13, 'MARKETER_WITHDRAW'), (14, 'MARKETER_ALIPAY_ACCOUNT_AUTH')]),
        ),
    ]
