# Generated by Django 2.0.4 on 2018-10-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0033_auto_20181010_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketer',
            name='wechat_nickname',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
