# Generated by Django 2.0.4 on 2018-10-17 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0034_marketer_wechat_nickname'),
        ('common', '0033_auto_20181011_1129'),
    ]

    operations = [
    ]
