# Generated by Django 2.0.4 on 2018-10-24 14:54

import common.encrypt_fileds
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0035_merge_20181017_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('serial_number', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'PROCESSING'), (1, 'FINISHED')])),
                ('wechat_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('alipay_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AddField(
            model_name='merchant',
            name='type',
            field=models.IntegerField(choices=[(0, 'INDIVIDUAL'), (1, 'ENTERPRISE')], default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='bank_card_number',
            field=common.encrypt_fileds.EncryptedCharField(blank=True, db_index=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(0, 'PLATFORM_RECEIVE'), (1, 'PLATFORM_EXPEND_MERCHANT_RECEIVE'), (2, 'MERCHANT_RECEIVE'), (3, 'MERCHANT_REFUND'), (4, 'PLATFORM_EARNING_MERCHANT_REFUND'), (5, 'PLATFORM_REFUND'), (6, 'PLATFORM_EXPEND_MERCHANT_SHARE'), (7, 'MERCHANT_SHARE'), (8, 'PLATFORM_EXPEND_MARKETER_SHARE'), (9, 'MARKETER_SHARE'), (10, 'PLATFORM_EXPEND_PLATFORM_SHARE'), (11, 'PLATFORM_SHARE'), (12, 'MERCHANT_WITHDRAW'), (13, 'MARKETER_WITHDRAW'), (14, 'MARKETER_ALIPAY_ACCOUNT_AUTH'), (15, 'MERCHANT_WECHAT_SETTLEMENT'), (16, 'MERCHANT_ALIPAY_SETTLEMENT')]),
        ),
        migrations.AddField(
            model_name='settlement',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.Account'),
        ),
    ]
