# Generated by Django 2.0.4 on 2018-11-02 10:37

import common.encrypt_fileds
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0036_auto_20181024_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedBankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=128, null=True)),
                ('bank_card_number', common.encrypt_fileds.EncryptedCharField(blank=True, db_index=True, max_length=128, null=True, unique=True)),
                ('real_name', models.CharField(blank=True, max_length=128, null=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('marketer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Marketer')),
            ],
        ),
    ]
