# Generated by Django 2.0.4 on 2018-11-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0038_merchantadmin_voice_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiedbankaccount',
            name='request_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='verifiedbankaccount',
            name='verify_status',
            field=models.IntegerField(choices=[(0, 'VERIFYING'), (1, 'SUCCESS'), (2, 'FAIL')], default=0),
        ),
    ]
