# Generated by Django 2.0.4 on 2018-11-12 14:03

import common.encrypt_fileds
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0039_auto_20181107_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifiedbankaccount',
            name='bank_card_number',
            field=common.encrypt_fileds.EncryptedCharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='verifiedbankaccount',
            unique_together={('bank_name', 'bank_card_number', 'real_name')},
        ),
    ]
